-- PRISM Deployment - Step 1: Prerequisites
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS IDENTIFIER($PRISM_APP_ROLE) COMMENT = 'PRISM application role';
CREATE ROLE IF NOT EXISTS IDENTIFIER($PRISM_GOV_ROLE) COMMENT = 'PRISM governance role';
GRANT ROLE IDENTIFIER($PRISM_APP_ROLE) TO ROLE SYSADMIN;
GRANT ROLE IDENTIFIER($PRISM_APP_ROLE) TO ROLE IDENTIFIER($PRISM_GOV_ROLE);
GRANT ROLE IDENTIFIER($PRISM_GOV_ROLE) TO ROLE ACCOUNTADMIN;

GRANT CREATE DATABASE ON ACCOUNT TO ROLE IDENTIFIER($PRISM_APP_ROLE);
GRANT CREATE ROLE ON ACCOUNT TO ROLE IDENTIFIER($PRISM_APP_ROLE);
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE IDENTIFIER($PRISM_APP_ROLE);
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE IDENTIFIER($PRISM_APP_ROLE);
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE IDENTIFIER($PRISM_APP_ROLE);
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE IDENTIFIER($PRISM_APP_ROLE);

GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE IDENTIFIER($PRISM_GOV_ROLE);
GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE IDENTIFIER($PRISM_GOV_ROLE);
GRANT APPLY TAG ON ACCOUNT TO ROLE IDENTIFIER($PRISM_GOV_ROLE);

GRANT ROLE IDENTIFIER($PRISM_APP_ROLE) TO USER IDENTIFIER($PRISM_ADMIN_USER);
GRANT ROLE IDENTIFIER($PRISM_GOV_ROLE) TO USER IDENTIFIER($PRISM_ADMIN_USER);

SELECT 'Step 1 complete.' AS STATUS;
