-- PRISM Deployment - Step 2: Databases & Schemas
USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS IDENTIFIER($PRISM_SECURITY_DB);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($PRISM_SECURITY_DB || '.' || $PRISM_SECURITY_SCHEMA);
USE SCHEMA IDENTIFIER($PRISM_SECURITY_DB || '.' || $PRISM_SECURITY_SCHEMA);
CREATE STAGE IF NOT EXISTS IDENTIFIER($PRISM_STREAMLIT_STAGE);
CREATE FILE FORMAT IF NOT EXISTS PYFORMAT TYPE=CSV FIELD_DELIMITER=NONE RECORD_DELIMITER='\n' SKIP_HEADER=0 FIELD_OPTIONALLY_ENCLOSED_BY=NONE ESCAPE_UNENCLOSED_FIELD=NONE;

CREATE DATABASE IF NOT EXISTS IDENTIFIER($PRISM_OPERATIONS_DB);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($PRISM_OPERATIONS_DB || '.' || $PRISM_OPERATIONS_SCHEMA);

CREATE DATABASE IF NOT EXISTS IDENTIFIER($PRISM_HORIZON_DB);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($PRISM_HORIZON_DB || '.TAGS');
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($PRISM_HORIZON_DB || '.POLICIES');
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($PRISM_HORIZON_DB || '.AUDIT');
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($PRISM_HORIZON_DB || '.CLASSIFICATION');

GRANT OWNERSHIP ON DATABASE IDENTIFIER($PRISM_SECURITY_DB) TO ROLE IDENTIFIER($PRISM_APP_ROLE) COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE IDENTIFIER($PRISM_OPERATIONS_DB) TO ROLE IDENTIFIER($PRISM_APP_ROLE) COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE IDENTIFIER($PRISM_HORIZON_DB) TO ROLE IDENTIFIER($PRISM_APP_ROLE) COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE IDENTIFIER($PRISM_SECURITY_DB) TO ROLE IDENTIFIER($PRISM_APP_ROLE) COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE IDENTIFIER($PRISM_OPERATIONS_DB) TO ROLE IDENTIFIER($PRISM_APP_ROLE) COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE IDENTIFIER($PRISM_HORIZON_DB) TO ROLE IDENTIFIER($PRISM_APP_ROLE) COPY CURRENT GRANTS;

GRANT USAGE ON DATABASE IDENTIFIER($PRISM_HORIZON_DB) TO ROLE IDENTIFIER($PRISM_GOV_ROLE);
GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER($PRISM_HORIZON_DB) TO ROLE IDENTIFIER($PRISM_GOV_ROLE);
GRANT USAGE ON DATABASE IDENTIFIER($PRISM_SECURITY_DB) TO ROLE IDENTIFIER($PRISM_GOV_ROLE);
GRANT USAGE ON SCHEMA IDENTIFIER($PRISM_SECURITY_DB || '.' || $PRISM_SECURITY_SCHEMA) TO ROLE IDENTIFIER($PRISM_GOV_ROLE);
GRANT USAGE ON WAREHOUSE IDENTIFIER($PRISM_WAREHOUSE) TO ROLE IDENTIFIER($PRISM_APP_ROLE);
GRANT USAGE ON WAREHOUSE IDENTIFIER($PRISM_WAREHOUSE) TO ROLE IDENTIFIER($PRISM_GOV_ROLE);

SELECT 'Step 2 complete.' AS STATUS;
