-- ============================================================
-- PRISM Deployment - Step 3: Tables & Sequences
-- ============================================================

USE ROLE IDENTIFIER($PRISM_APP_ROLE);

-- ============================================================
-- 3.1 Security Database Tables
-- ============================================================
USE SCHEMA IDENTIFIER($PRISM_SECURITY_DB || '.' || $PRISM_SECURITY_SCHEMA);

-- ENVIRONMENTS
CREATE TABLE IF NOT EXISTS ENVIRONMENTS (
	ENVIRONMENT_NAME VARCHAR(16777216) NOT NULL COMMENT 'Name of the environment (e.g., DEV, SYS, UAT, PROD)',
	primary key (ENVIRONMENT_NAME)
);

-- ACCESS_PROFILES
CREATE TABLE IF NOT EXISTS ACCESS_PROFILES (
	ACCESS_CODE VARCHAR(10) NOT NULL,
	ROLE_SUFFIX VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(500) NOT NULL,
	HIERARCHY_PARENT VARCHAR(10),
	HIERARCHY_ORDER NUMBER(38,0) NOT NULL,
	GRANT_SCOPE VARCHAR(20) NOT NULL DEFAULT 'ALL+FUTURE',
	APPLIES_AT VARCHAR(20) NOT NULL DEFAULT 'DATABASE+SCHEMA',
	IS_SYSTEM_ONLY BOOLEAN NOT NULL DEFAULT FALSE,
	IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(100) NOT NULL DEFAULT CURRENT_USER(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	UPDATED_BY VARCHAR(100),
	constraint PK_ACCESS_PROFILES primary key (ACCESS_CODE)
)COMMENT='Defines access profiles (role templates) and their hierarchy. HIERARCHY_PARENT defines role inheritance chain.';

-- ACCESS_PROFILE_PRIVILEGES
CREATE TABLE IF NOT EXISTS ACCESS_PROFILE_PRIVILEGES (
	ACCESS_CODE VARCHAR(10) NOT NULL,
	OBJECT_TYPE VARCHAR(100) NOT NULL,
	PRIVILEGE VARCHAR(100) NOT NULL,
	GRANT_TARGET VARCHAR(20) NOT NULL DEFAULT 'DATABASE',
	IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	ADDED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ADDED_BY VARCHAR(100) NOT NULL DEFAULT CURRENT_USER(),
	NOTES VARCHAR(500),
	constraint PK_PROFILE_PRIVILEGES primary key (ACCESS_CODE, OBJECT_TYPE, PRIVILEGE, GRANT_TARGET),
	constraint FK_ACCESS_CODE foreign key (ACCESS_CODE) references ACCESS_PROFILES(ACCESS_CODE)
)COMMENT='Maps each access profile to specific privileges per object type. One row per privilege — no comma-separated values. GRANT_TARGET = DATABASE or SCHEMA.';

-- SNOWFLAKE_PRIVILEGE_CATALOG
CREATE TABLE IF NOT EXISTS SNOWFLAKE_PRIVILEGE_CATALOG (
	OBJECT_TYPE VARCHAR(100) NOT NULL,
	OBJECT_TYPE_PLURAL VARCHAR(100) NOT NULL,
	PARENT_SCOPE VARCHAR(50) NOT NULL,
	PRIVILEGE VARCHAR(100) NOT NULL,
	SUPPORTS_ALL BOOLEAN NOT NULL DEFAULT FALSE,
	SUPPORTS_FUTURE BOOLEAN NOT NULL DEFAULT FALSE,
	SUPPORTS_INHERITED BOOLEAN NOT NULL DEFAULT FALSE,
	LAST_SYNCED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	SYNCED_BY VARCHAR(100) NOT NULL DEFAULT CURRENT_USER(),
	constraint PK_PRIVILEGE_CATALOG primary key (OBJECT_TYPE, PRIVILEGE, PARENT_SCOPE)
)COMMENT='Auto-populated from EXPLAIN_GRANTABLE_PRIVILEGES(). Source of truth for all Snowflake grantable privileges. Do not manually edit.';

-- ENVIRONMENT_ROLE_METADATA
CREATE TABLE IF NOT EXISTS ENVIRONMENT_ROLE_METADATA (
	ROLE_TEMPLATE VARCHAR(50) NOT NULL,
	PARENT_SYSTEM_ROLE VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(500) NOT NULL,
	OWNS_DATABASES BOOLEAN NOT NULL DEFAULT FALSE,
	OWNS_SCHEMAS BOOLEAN NOT NULL DEFAULT FALSE,
	OWNS_DB_ROLES BOOLEAN NOT NULL DEFAULT FALSE,
	OWNS_ACCOUNT_ROLES BOOLEAN NOT NULL DEFAULT FALSE,
	HIERARCHY_ORDER NUMBER(38,0) NOT NULL,
	IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(100) NOT NULL DEFAULT CURRENT_USER(),
	constraint PK_ENV_ROLE_METADATA primary key (ROLE_TEMPLATE)
)COMMENT='Defines per-environment account-level roles. ROLE_TEMPLATE uses <ENV> as placeholder. E.g. <ENV>_SYSADMIN becomes DEV_SYSADMIN.';

-- FUNCTIONAL_TECHNICAL_ROLE_METADATA
CREATE TABLE IF NOT EXISTS FUNCTIONAL_TECHNICAL_ROLE_METADATA (
	FUNCTION_NAME VARCHAR(16777216) NOT NULL COMMENT 'Name of the function (e.g., DEVELOPER, ETL, BUSINESS_ANALYST)',
	ROLE_TYPE VARCHAR(16777216) NOT NULL COMMENT 'Type of role: ''Functional'' or ''Technical''',
	PREFIX_PATTERN VARCHAR(16777216) NOT NULL COMMENT 'Pattern for the role prefix, e.g., ''<ENV>_'' where <ENV> is a placeholder',
	SUFFIX VARCHAR(16777216) NOT NULL COMMENT 'Suffix for the role, e.g., ''_FR'' for Functional Role, ''_TR'' for Technical Role',
	primary key (FUNCTION_NAME, ROLE_TYPE)
)COMMENT='Metadata for defining functional and technical role naming conventions. Prefix <ENV> will be replaced by actual environment name.';

-- WAREHOUSE_METADATA
CREATE TABLE IF NOT EXISTS WAREHOUSE_METADATA (
	WAREHOUSE_TYPE VARCHAR(50) NOT NULL,
	WAREHOUSE_SIZE VARCHAR(20) NOT NULL,
	WAREHOUSE_CLASS VARCHAR(30) NOT NULL DEFAULT 'STANDARD',
	DEFAULT_AUTO_SUSPEND_SECS NUMBER(38,0) NOT NULL DEFAULT 600,
	DEFAULT_AUTO_RESUME BOOLEAN NOT NULL DEFAULT TRUE,
	DEFAULT_INITIALLY_SUSPENDED BOOLEAN NOT NULL DEFAULT TRUE,
	DEFAULT_MIN_CLUSTER_COUNT NUMBER(38,0) NOT NULL DEFAULT 1,
	DEFAULT_MAX_CLUSTER_COUNT NUMBER(38,0) NOT NULL DEFAULT 1,
	DEFAULT_SCALING_POLICY VARCHAR(20) NOT NULL DEFAULT 'STANDARD',
	DEFAULT_ENABLE_QUERY_ACCELERATION BOOLEAN NOT NULL DEFAULT FALSE,
	DEFAULT_QUERY_ACCEL_MAX_SCALE NUMBER(38,0) NOT NULL DEFAULT 8,
	DEFAULT_STATEMENT_TIMEOUT_SECS NUMBER(38,0) NOT NULL DEFAULT 172800,
	DEFAULT_STMT_QUEUED_TIMEOUT_SECS NUMBER(38,0) NOT NULL DEFAULT 0,
	DEFAULT_MAX_CONCURRENCY_LEVEL NUMBER(38,0) NOT NULL DEFAULT 8,
	DEFAULT_RESOURCE_MONITOR VARCHAR(100),
	DEFAULT_COMMENT VARCHAR(500),
	WAREHOUSE_NAME_PATTERN VARCHAR(100) NOT NULL DEFAULT '<ENV>_<TYPE>_<SIZE>_WH',
	IS_CUSTOM BOOLEAN NOT NULL DEFAULT FALSE,
	IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER(),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_BY VARCHAR(100),
	UPDATED_AT TIMESTAMP_NTZ(9),
	constraint PK_WAREHOUSE_METADATA primary key (WAREHOUSE_TYPE, WAREHOUSE_SIZE, WAREHOUSE_CLASS)
)COMMENT='Comprehensive warehouse configuration metadata. All Snowflake warehouse options are metadata-driven. WAREHOUSE_NAME_PATTERN supports <ENV>, <TYPE>, <SIZE>, <CUSTOM> placeholders.';

-- ============================================================
-- 3.2 Operations Database Tables
-- ============================================================
USE SCHEMA IDENTIFIER($PRISM_OPERATIONS_DB || '.' || $PRISM_OPERATIONS_SCHEMA);

CREATE SEQUENCE IF NOT EXISTS SEQ_AUDIT_LOG START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_ROLE_HIERARCHY_LOG START = 1 INCREMENT = 1;

-- AUDIT_LOG
CREATE TABLE IF NOT EXISTS AUDIT_LOG (
	EVENT_ID NUMBER(38,0) COMMENT 'ID for the entire execution',
	EVENT_TIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP() COMMENT 'Timestamp of the event',
	INVOKED_BY VARCHAR(16777216) COMMENT 'User who invoked the stored procedure',
	EVENT_TYPE VARCHAR(16777216) COMMENT 'Type of event (e.g., CREATE_ROLE, GRANT_PRIVILEGE)',
	OBJECT_NAME VARCHAR(16777216) COMMENT 'Name of the object being affected (role, database, etc.)',
	SQL_COMMAND VARCHAR(16777216) COMMENT 'The SQL command executed',
	STATUS VARCHAR(16777216) COMMENT 'Status of the command execution (SUCCESS, ERROR)',
	MESSAGE VARCHAR(16777216) COMMENT 'Additional message or error details'
);

-- ROLE_HIERARCHY_LOG
CREATE TABLE IF NOT EXISTS ROLE_HIERARCHY_LOG (
	LOG_ID NUMBER(38,0) NOT NULL  COMMENT 'Unique ID for this log entry',
	EVENT_TIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP() COMMENT 'Timestamp of the event',
	AUDIT_EVENT_ID NUMBER(38,0) COMMENT 'Corresponds to EVENT_ID in AUDIT_LOG for the broader operation, linking logs',
	INVOKED_BY VARCHAR(16777216) COMMENT 'User who invoked the procedure that triggered this log entry',
	ENVIRONMENT_NAME VARCHAR(16777216) COMMENT 'Environment in which the role was created (e.g., DEV, SYS, UAT, PROD)',
	CREATED_ROLE_NAME VARCHAR(16777216) COMMENT 'The full name of the functional or technical account-level role created (e.g., DEV_DEVELOPER_FR)',
	CREATED_ROLE_TYPE VARCHAR(16777216) COMMENT 'Type of role created (Functional or Technical)',
	MAPPED_DATABASE_ROLE VARCHAR(16777216) COMMENT 'The fully qualified database role granted to the CREATED_ROLE_NAME (e.g., \"DEV_DB1_DB\".\"RO_AR\")',
	PARENT_ACCOUNT_ROLE VARCHAR(16777216) COMMENT 'The account-level role that owns the CREATED_ROLE_NAME (e.g., DEV_USERADMIN)',
	SQL_COMMAND_CREATE_ROLE VARCHAR(16777216) COMMENT 'The SQL command used to create the functional/technical role',
	SQL_COMMAND_GRANT_DB_ROLE VARCHAR(16777216) COMMENT 'The SQL command used to grant the database role to the functional/technical role',
	STATUS VARCHAR(16777216) COMMENT 'Status of the operation for this specific role (SUCCESS, ERROR)',
	MESSAGE VARCHAR(16777216) COMMENT 'Additional message or error details related to this specific role operation',
	primary key (LOG_ID)
)COMMENT='Logs the creation of functional/technical roles and their mapping to database roles, including hierarchy.';

-- ============================================================
-- 3.3 Horizon Database Tables
-- ============================================================

USE SCHEMA IDENTIFIER($PRISM_HORIZON_DB || '.AUDIT');
CREATE SEQUENCE IF NOT EXISTS SEQ_GOV_AUDIT START = 1 INCREMENT = 1;

USE SCHEMA IDENTIFIER($PRISM_HORIZON_DB || '.AUDIT');
CREATE TABLE IF NOT EXISTS GOV_AUDIT_LOG (
	AUDIT_ID NUMBER(38,0) NOT NULL,
	EVENT_TIME TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	INVOKED_BY VARCHAR(256) NOT NULL,
	EVENT_TYPE VARCHAR(100) NOT NULL,
	OBJECT_DATABASE VARCHAR(256),
	OBJECT_SCHEMA VARCHAR(256),
	OBJECT_NAME VARCHAR(256),
	OBJECT_TYPE VARCHAR(50),
	ACTION_DETAIL VARCHAR(4000),
	SQL_COMMAND VARCHAR(16000),
	STATUS VARCHAR(20) NOT NULL,
	MESSAGE VARCHAR(4000)
)COMMENT='Governance audit log for all tag, policy, and classification operations.';

USE SCHEMA IDENTIFIER($PRISM_HORIZON_DB || '.TAGS');
CREATE TABLE IF NOT EXISTS TAG_REGISTRY (
	TAG_DATABASE VARCHAR(256) NOT NULL,
	TAG_SCHEMA VARCHAR(256) NOT NULL,
	TAG_NAME VARCHAR(256) NOT NULL,
	TAG_COMMENT VARCHAR(4000),
	ALLOWED_VALUES VARIANT,
	CREATED_BY VARCHAR(256) NOT NULL DEFAULT CURRENT_USER(),
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	constraint PK_TAG_REGISTRY primary key (TAG_DATABASE, TAG_SCHEMA, TAG_NAME)
)COMMENT='Registry of all governance tags managed through PRISM.';

USE SCHEMA IDENTIFIER($PRISM_HORIZON_DB || '.POLICIES');
CREATE TABLE IF NOT EXISTS POLICY_REGISTRY (
	POLICY_DATABASE VARCHAR(256) NOT NULL,
	POLICY_SCHEMA VARCHAR(256) NOT NULL,
	POLICY_NAME VARCHAR(256) NOT NULL,
	POLICY_TYPE VARCHAR(50) NOT NULL,
	POLICY_BODY VARCHAR(16000),
	TARGET_DATA_TYPE VARCHAR(50),
	POLICY_COMMENT VARCHAR(4000),
	CREATED_BY VARCHAR(256) NOT NULL DEFAULT CURRENT_USER(),
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	constraint PK_POLICY_REGISTRY primary key (POLICY_DATABASE, POLICY_SCHEMA, POLICY_NAME)
)COMMENT='Registry of all masking policies, row access policies, and other governance policies managed through PRISM.';

USE SCHEMA IDENTIFIER($PRISM_HORIZON_DB || '.POLICIES');
CREATE TABLE IF NOT EXISTS MASKING_POLICY_TEMPLATES (
	TEMPLATE_NAME VARCHAR(100) NOT NULL,
	DATA_TYPE VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(500) NOT NULL,
	POLICY_BODY_TEMPLATE VARCHAR(8000) NOT NULL,
	MASKED_VALUE_EXAMPLE VARCHAR(200),
	IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	constraint PK_MASKING_TEMPLATES primary key (TEMPLATE_NAME, DATA_TYPE)
)COMMENT='Pre-built masking policy templates for common data types and patterns.';

-- PRISM Settings (stores deployment configuration)
USE SCHEMA IDENTIFIER($PRISM_SECURITY_DB || '.' || $PRISM_SECURITY_SCHEMA);
CREATE TABLE IF NOT EXISTS PRISM_SETTINGS (
    SETTING_KEY     VARCHAR(100) NOT NULL,
    SETTING_VALUE   VARCHAR(500) NOT NULL,
    DESCRIPTION     VARCHAR(500),
    UPDATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY      VARCHAR(256) DEFAULT 'SYSTEM',
    CONSTRAINT PK_PRISM_SETTINGS PRIMARY KEY (SETTING_KEY)
);

SELECT 'Step 3 complete: All tables and sequences created.' AS STATUS;
