-- PRISM Deployment - Step 5: Views
USE ROLE IDENTIFIER($PRISM_APP_ROLE);
USE SCHEMA IDENTIFIER($PRISM_SECURITY_DB || '.' || $PRISM_SECURITY_SCHEMA);

CREATE OR REPLACE VIEW V_PRIVILEGE_DRIFT AS SELECT c.OBJECT_TYPE, c.PRIVILEGE, c.PARENT_SCOPE FROM SNOWFLAKE_PRIVILEGE_CATALOG c LEFT JOIN ACCESS_PROFILE_PRIVILEGES p ON c.OBJECT_TYPE = p.OBJECT_TYPE AND c.PRIVILEGE = p.PRIVILEGE WHERE p.PRIVILEGE IS NULL AND c.PARENT_SCOPE IN ('SCHEMA','DATABASE') ORDER BY 1, 2;

CREATE OR REPLACE VIEW V_PROFILE_PRIVILEGE_SUMMARY AS SELECT p.ACCESS_CODE, ap.ROLE_SUFFIX, ap.DESCRIPTION AS PROFILE_DESCRIPTION, p.OBJECT_TYPE, p.PRIVILEGE, p.GRANT_TARGET, p.IS_ACTIVE FROM ACCESS_PROFILE_PRIVILEGES p JOIN ACCESS_PROFILES ap ON p.ACCESS_CODE = ap.ACCESS_CODE ORDER BY ap.HIERARCHY_ORDER, p.OBJECT_TYPE, p.PRIVILEGE;

CREATE OR REPLACE VIEW V_ROLE_HIERARCHY AS SELECT child.ACCESS_CODE AS CHILD_PROFILE, child.ROLE_SUFFIX AS CHILD_SUFFIX, parent.ACCESS_CODE AS PARENT_PROFILE, parent.ROLE_SUFFIX AS PARENT_SUFFIX, child.HIERARCHY_ORDER FROM ACCESS_PROFILES child JOIN ACCESS_PROFILES parent ON child.HIERARCHY_PARENT = parent.ACCESS_CODE WHERE child.IS_ACTIVE = TRUE AND parent.IS_ACTIVE = TRUE ORDER BY child.HIERARCHY_ORDER;

CREATE OR REPLACE VIEW V_OWNERSHIP_MIGRATION_PLAN AS SELECT ROLE_TEMPLATE, PARENT_SYSTEM_ROLE, OWNS_DATABASES, OWNS_SCHEMAS, OWNS_DB_ROLES, OWNS_ACCOUNT_ROLES, DESCRIPTION FROM ENVIRONMENT_ROLE_METADATA WHERE IS_ACTIVE = TRUE ORDER BY HIERARCHY_ORDER;

SELECT 'Step 5 complete.' AS STATUS;
