-- PRISM Deployment - Step 8: Streamlit App
-- BEFORE RUNNING: Upload streamlit files to the stage:
-- PUT file://streamlit/streamlit_app.py @<DB>.<SCHEMA>.<STAGE>/ OVERWRITE=TRUE AUTO_COMPRESS=FALSE;
-- PUT file://streamlit/environment.yml @<DB>.<SCHEMA>.<STAGE>/ OVERWRITE=TRUE AUTO_COMPRESS=FALSE;
-- PUT file://streamlit/NTT-Data-Logo.png @<DB>.<SCHEMA>.<STAGE>/ OVERWRITE=TRUE AUTO_COMPRESS=FALSE;

USE ROLE IDENTIFIER($PRISM_APP_ROLE);
USE SCHEMA IDENTIFIER($PRISM_STREAMLIT_DB || '.' || $PRISM_STREAMLIT_SCHEMA);

LIST @IDENTIFIER($PRISM_STREAMLIT_STAGE);

CREATE OR REPLACE STREAMLIT IDENTIFIER($PRISM_STREAMLIT_NAME) ROOT_LOCATION = '@' || $PRISM_STREAMLIT_DB || '.' || $PRISM_STREAMLIT_SCHEMA || '.' || $PRISM_STREAMLIT_STAGE MAIN_FILE = 'streamlit_app.py' QUERY_WAREHOUSE = $PRISM_WAREHOUSE TITLE = 'PRISM' COMMENT = 'Portal for Role Integration, Security & Management v2.0.0';

GRANT USAGE ON STREAMLIT IDENTIFIER($PRISM_STREAMLIT_NAME) TO ROLE IDENTIFIER($PRISM_APP_ROLE);

SELECT 'Step 8 complete.' AS STATUS;
