-- PRISM Deployment - Step 9: Tasks
USE ROLE IDENTIFIER($PRISM_APP_ROLE);
USE SCHEMA IDENTIFIER($PRISM_SECURITY_DB || '.' || $PRISM_SECURITY_SCHEMA);

CREATE OR REPLACE TASK TASK_SYNC_PRIVILEGE_CATALOG WAREHOUSE = $PRISM_WAREHOUSE SCHEDULE = $PRISM_CATALOG_SYNC_SCHEDULE COMMENT = 'Weekly sync of Snowflake privilege catalog' AS CALL SP_SYNC_PRIVILEGE_CATALOG();
ALTER TASK TASK_SYNC_PRIVILEGE_CATALOG RESUME;

SELECT 'Step 9 complete.' AS STATUS;
