-- PRISM Deployment - Step 10: Post-Install Verification
USE ROLE IDENTIFIER($PRISM_APP_ROLE);
USE SCHEMA IDENTIFIER($PRISM_SECURITY_DB || '.' || $PRISM_SECURITY_SCHEMA);

CALL SP_SYNC_PRIVILEGE_CATALOG();

SELECT 'ACCESS_PROFILES' AS TBL, COUNT(*) AS ROWS FROM ACCESS_PROFILES UNION ALL SELECT 'PRIVILEGES', COUNT(*) FROM ACCESS_PROFILE_PRIVILEGES UNION ALL SELECT 'ENVIRONMENTS', COUNT(*) FROM ENVIRONMENTS UNION ALL SELECT 'WAREHOUSE_METADATA', COUNT(*) FROM WAREHOUSE_METADATA UNION ALL SELECT 'PRIVILEGE_CATALOG', COUNT(*) FROM SNOWFLAKE_PRIVILEGE_CATALOG ORDER BY 1;

SELECT * FROM V_ROLE_HIERARCHY;

SELECT 'PRISM v' || $PRISM_VERSION || ' installed successfully!' AS STATUS;
