-- PRISM Deployment - Configuration
-- Edit these variables before running the installer

SET PRISM_SECURITY_DB = 'PRISM_SECURITY';
SET PRISM_SECURITY_SCHEMA = 'ACCESS_CONTROL';
SET PRISM_OPERATIONS_DB = 'PRISM_OPERATIONS';
SET PRISM_OPERATIONS_SCHEMA = 'LOGS';
SET PRISM_HORIZON_DB = 'PRISM_HORIZON';
SET PRISM_WAREHOUSE = 'COMPUTE_WH';
SET PRISM_APP_ROLE = 'PRISM_APP_ROLE';
SET PRISM_GOV_ROLE = 'PRISM_GOV_ROLE';
SET PRISM_ADMIN_USER = 'ADMIN';
SET PRISM_STREAMLIT_DB = 'PRISM_SECURITY';
SET PRISM_STREAMLIT_SCHEMA = 'ACCESS_CONTROL';
SET PRISM_STREAMLIT_NAME = 'PRISM_APP';
SET PRISM_STREAMLIT_STAGE = 'PRISM_APP_STAGE';
SET PRISM_CATALOG_SYNC_SCHEDULE = 'USING CRON 0 2 * * 0 UTC';
SET PRISM_VERSION = '2.0.0';
