-- PRISM Uninstall - Removes all PRISM objects
-- WARNING: This permanently deletes all PRISM data!

USE ROLE ACCOUNTADMIN;

ALTER TASK IF EXISTS IDENTIFIER($PRISM_SECURITY_DB || '.' || $PRISM_SECURITY_SCHEMA || '.TASK_SYNC_PRIVILEGE_CATALOG') SUSPEND;
DROP TASK IF EXISTS IDENTIFIER($PRISM_SECURITY_DB || '.' || $PRISM_SECURITY_SCHEMA || '.TASK_SYNC_PRIVILEGE_CATALOG');
DROP STREAMLIT IF EXISTS IDENTIFIER($PRISM_STREAMLIT_DB || '.' || $PRISM_STREAMLIT_SCHEMA || '.' || $PRISM_STREAMLIT_NAME);
DROP DATABASE IF EXISTS IDENTIFIER($PRISM_SECURITY_DB);
DROP DATABASE IF EXISTS IDENTIFIER($PRISM_OPERATIONS_DB);
DROP DATABASE IF EXISTS IDENTIFIER($PRISM_HORIZON_DB);
DROP ROLE IF EXISTS IDENTIFIER($PRISM_GOV_ROLE);
DROP ROLE IF EXISTS IDENTIFIER($PRISM_APP_ROLE);

SELECT 'PRISM uninstalled.' AS STATUS;
